<a href="https://colab.research.google.com/github/harshaanth/python-coding-exercises/blob/main/Coding_Exercises_Intro_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Guided Coding Exercises: Intro Python
In these exercises, we will practice the methods covered in the DataCamp course, Introduction to Python. The application involves working with a small data set containing information about electric cars. The goal is to gain experience and confidence working with lists and numpy arrays, two popular tools for organizing information in Python.

Here we define a list called `total_sales` to contain the models of electric cars and the number of units sold.

In [ ]:
# 3 year total sales in thousands of units
total_sales=["Tesla3",296, "TeslaS", 67, "TeslaX", 67, "Bolt", 58, "Leaf", 38, "BMW_i3", 17, "e-Golf", 10]

print(total_sales)

['Tesla3', 296, 'TeslaS', 67, 'TeslaX', 67, 'Bolt', 58, 'Leaf', 38, 'BMW_i3', 17, 'e-Golf', 10]


Here we define a list called `price` to contain the typical retail price for each model in thousands of US dollars.

In [ ]:
# Typical Retail Price in $thousands USD
price=["Tesla3", 47, "TeslaS", 89, "TeslaX", 99, "Bolt", 32, "Leaf", 27, "BMW_i3", 83, "e-Golf", 45]

print(price)

['Tesla3', 47, 'TeslaS', 89, 'TeslaX', 99, 'Bolt', 32, 'Leaf', 27, 'BMW_i3', 83, 'e-Golf', 45]


Use indexing to access the total sales for the TeslaS model.

In [ ]:
# Use indexing to access the total sales for the TeslaS model
total_sales[3]

67

Expected Output:
```
67
```

Use indexing to access the last element in the price list.

In [ ]:
# Use indexing to access the last element in the price list.
price[-1]

45

Expected Output:
```
45
```

Multiply the TeslaS total sales by the TeslaS retail price (use indexing) call this value `TeslaS_revenue`.


In [ ]:
# Multiply the TeslaS total sales by the TeslaS retail price (use indexing) call this value TeslaS_revenue
TeslaS_revenue=total_sales[3]*price[3]
print(TeslaS_revenue)

5963


Expected Output:
```
5963
```

Suppose we need to update the list with another electric car. Run the code below to define the new variables to store the model and the number of units sold, and the model and the price in thousands of US dollars.



In [ ]:
# Fiat data
fiat_total=["Fiat_500E",6]
fiat_price=["Fiat_500E", 27]

Add the fiat total to the total_sales list

In [ ]:
# Add the fiat total to the total_sales list
total_sales=total_sales+fiat_total
print(total_sales)

['Tesla3', 296, 'TeslaS', 67, 'TeslaX', 67, 'Bolt', 58, 'Leaf', 38, 'BMW_i3', 17, 'e-Golf', 10, 'Fiat_500E', 6]


Expected Output:
```
['Tesla3', 296, 'TeslaS', 67, 'TeslaX', 67, 'Bolt', 58, 'Leaf', 38, 'BMW_i3', 17, 'e-Golf', 10, 'Fiat_500E', 6]
```

Add the fiat price to the price list.

In [ ]:
# Add the fiat price to the price list
price=price+fiat_price
print(price)

['Tesla3', 47, 'TeslaS', 89, 'TeslaX', 99, 'Bolt', 32, 'Leaf', 27, 'BMW_i3', 83, 'e-Golf', 45, 'Fiat_500E', 27]


Expected Output:
```
['Tesla3', 47, 'TeslaS', 89, 'TeslaX', 99, 'Bolt', 32, 'Leaf', 27, 'BMW_i3', 83, 'e-Golf', 45, 'Fiat_500E', 27]
```

Use slicing and stepping to create a list of just the total sale values and another list of just the prices without the model names.


In [ ]:
# Use slicing and stepping to create a list of just the total sale values and another list of just the prices without the model names.

total_sales_num=total_sales[1::2]
print(total_sales_num)

price_num=price[1::2]
print(price_num)

[296, 67, 67, 58, 38, 17, 10, 6]
[47, 89, 99, 32, 27, 83, 45, 27]


Expected Output:
```
[296, 67, 67, 58, 38, 17, 10, 6]
[47, 89, 99, 32, 27, 83, 45, 27]
```

Create a numpy array using the total sales values and the price values

In [ ]:
# Create a numpy array using the total sales values and the price values

import numpy as np
e_cars=np.array([total_sales_num,price_num]).transpose()
print(e_cars)

[[296  47]
 [ 67  89]
 [ 67  99]
 [ 58  32]
 [ 38  27]
 [ 17  83]
 [ 10  45]
 [  6  27]]


Expected Output:
```
[[296  47]
 [ 67  89]
 [ 67  99]
 [ 58  32]
 [ 38  27]
 [ 17  83]
 [ 10  45]
 [  6  27]]
```

Calculate all of the total revenue values

In [ ]:
# Calculate all of the total revenue values

revenue=e_cars[:,0]*e_cars[:,1]
print(revenue)

[13912  5963  6633  1856  1026  1411   450   162]


Expected Output:
```
[13912  5963  6633  1856  1026  1411   450   162]
```