<a href="https://colab.research.google.com/github/harshaanth/python-coding-exercises/blob/main/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Basics
These exercises are designed to reinforce the principles and methods introduced in the Introduction to Python DataCamp course. The numpy array is an important data object in Python and is used frequently to organize and work with data sets.

Create a variable called `baseball`, a list of lists each of which has a height in cm and a weight in kg

In [ ]:
# Create baseball, a list of lists each of which has a height in cm and a weight in kg
baseball = [[185, 78.4],
            [191, 102.7],
            [189, 98.5],
            [183, 85.2]]

Import the `numpy` library

In [ ]:
# Import numpy
import numpy as np

Create a 2D numpy array from baseball: np_baseball and print the result

In [ ]:
# Create a 2D numpy array from baseball: np_baseball and print the result
np_baseball=np.array(baseball)
print(np_baseball)

[[185.   78.4]
 [191.  102.7]
 [189.   98.5]
 [183.   85.2]]


Expected Output
```
[[185.   78.4]
 [191.  102.7]
 [189.   98.5]
 [183.   85.2]]
```

Print out the type of np_baseball

In [ ]:
# Print out the type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


Expected Output
```
<class 'numpy.ndarray'>
```

Print out the dimensions of the `np_baseball` array.

In [ ]:
# Print out the shape of np_baseball
print(np_baseball.shape)

(4, 2)


Expected Output
```
(4, 2)
```

Print out the third row of the baseball array

In [ ]:
# Print out the third row of the baseball array
print(np_baseball[2,:])

[189.   98.5]


Expected Output
```
[189.   98.5]
```

Print out the second column of the baseball array

In [ ]:
# Print out the second column of the baseball array
print(np_baseball[:,1])

[ 78.4 102.7  98.5  85.2]


Expected Output
```
[ 78.4 102.7  98.5  85.2]
```

Print out the weight of the third player (98.5)

In [ ]:
# Print out the weight of the third player (98.5)
print(np_baseball[2,1])

98.5


Expected Output
```
98.5
```

Create numpy array: conversion and print the result

In [ ]:
# Create numpy array: conversion
conversion=np.array([.394, 2.204])
print(conversion)

[0.394 2.204]


Expected Output
```
[0.394 2.204]
```

Print out product of np_baseball and conversion

In [ ]:
# Print out product of np_baseball and conversion
print(np_baseball*conversion)

[[ 72.89   172.7936]
 [ 75.254  226.3508]
 [ 74.466  217.094 ]
 [ 72.102  187.7808]]


Expected Output
```
[[ 72.89   172.7936]
 [ 75.254  226.3508]
 [ 74.466  217.094 ]
 [ 72.102  187.7808]]
```